// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaorzzjS3J530xdQBifSrUnhrI157sbPg',
    appId: '1:101868685859:web:b998708aa9c94ff1717f96',
    messagingSenderId: '101868685859',
    projectId: 'flutterdemo-fb8f8',
    authDomain: 'flutterdemo-fb8f8.firebaseapp.com',
    storageBucket: 'flutterdemo-fb8f8.firebasestorage.app',
    measurementId: 'G-LVGQSND4X3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMnpjKzFU98bLls95xmktLZUhYr6NkP20',
    appId: '1:101868685859:android:a6b1d3d7234baf21717f96',
    messagingSenderId: '101868685859',
    projectId: 'flutterdemo-fb8f8',
    storageBucket: 'flutterdemo-fb8f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVDcJOK0JzjRAju46cqtwUbiAQKDL9SjE',
    appId: '1:101868685859:ios:201e6665ec518502717f96',
    messagingSenderId: '101868685859',
    projectId: 'flutterdemo-fb8f8',
    storageBucket: 'flutterdemo-fb8f8.firebasestorage.app',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVDcJOK0JzjRAju46cqtwUbiAQKDL9SjE',
    appId: '1:101868685859:ios:201e6665ec518502717f96',
    messagingSenderId: '101868685859',
    projectId: 'flutterdemo-fb8f8',
    storageBucket: 'flutterdemo-fb8f8.firebasestorage.app',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaorzzjS3J530xdQBifSrUnhrI157sbPg',
    appId: '1:101868685859:web:c4bc16952488a84b717f96',
    messagingSenderId: '101868685859',
    projectId: 'flutterdemo-fb8f8',
    authDomain: 'flutterdemo-fb8f8.firebaseapp.com',
    storageBucket: 'flutterdemo-fb8f8.firebasestorage.app',
    measurementId: 'G-L9622410Q2',
  );
}
